https://github.com/Heemel33/Simulation-Modeling-Lab/upload/SIM_Lab1_Hasibul-Islam-Hemel_0432310005101005

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

Scalar & Array Operations (Redo Section with Your Own Values):
Run the given code with scalar = 3.7 and a new array of at least 6 elements.


Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).




In [2]:
# Sample scalar and array inputs
scaler = 3.7
arr = np.array([8, 9, 4, 2, 3, 7])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)


sin: [-0.2794155  -0.95892427 -0.7568025   0.14112001  0.90929743  0.84147098]
cos: [ 0.96017029  0.28366219 -0.65364362 -0.9899925  -0.41614684  0.54030231]
tan: [-0.29100619 -3.38051501  1.15782128 -0.14254654 -2.18503986  1.55740772]
asin: [1.57079633 0.98511078 0.72972766 0.52359878 0.33983691 0.16744808]
acos: [0.         0.58568554 0.84106867 1.04719755 1.23095942 1.40334825]
atan: [1.40564765 1.37340077 1.32581766 1.24904577 1.10714872 0.78539816]


2×2 Matrix Calculations (Already Done in Class):
Study and understand the example code given for trigonometric, exponential, logarithmic, and rounding operations on a 2×2 matrix.


Task: Apply the Same Operations on a 3×2 Matrix
Create a 3×2 matrix with custom values.


Perform and display results of:


Trigonometric functions


Exponential & logarithmic functions


Absolute value & square root


Remainder when divided by 2


Rounding (round, floor, ceil)


📌 Make sure to clip inputs where needed to avoid math errors (e.g., arcsin/arccos domain issues).


In [4]:
# Creating a 3x2 matrix
matrix = np.array([[2.7, 4], [4.9, 3], [8.5, 9]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)




Matrix:
 [[2.7 4. ]
 [4.9 3. ]
 [8.5 9. ]]

sin:
 [[ 0.42737988 -0.7568025 ]
 [-0.98245261  0.14112001]
 [ 0.79848711  0.41211849]]

cos:
 [[-0.90407214 -0.65364362]
 [ 0.18651237 -0.9899925 ]
 [-0.6020119  -0.91113026]]

tan:
 [[-0.47272763  1.15782128]
 [-5.26749307 -0.14254654]
 [-1.32636433 -0.45231566]]

asine:
 [[0.30469265 0.46055399]
 [0.57572665 0.33983691]
 [1.23590017 1.57079633]]

acosine:
 [[1.26610367 1.11024234]
 [0.99506968 1.23095942]
 [0.33489616 0.        ]]

atangent:
 [[1.21609067 1.32581766]
 [1.36947922 1.24904577]
 [1.45368758 1.46013911]]

exp:
 [[  14.87973172   54.59815003]
 [ 134.28977968   20.08553692]
 [4914.7688403  8103.08392758]]

log (natural):
 [[0.99325177 1.38629436]
 [1.58923521 1.09861229]
 [2.14006616 2.19722458]]

abs:
 [[2.7 4. ]
 [4.9 3. ]
 [8.5 9. ]]

sqrt:
 [[1.64316767 2.        ]
 [2.21359436 1.73205081]
 [2.91547595 3.        ]]

rem (remainder when divided by 2):
 [[0.7 0. ]
 [0.9 1. ]
 [0.5 1. ]]

round:
 [[3. 4.]
 [5. 3.]
 [8. 9.]]

fl

Vector Functions
Understand the operations on the 1D vector shown in the notebook.


Task: Perform Same Operations on a 2×3 Matrix
Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).


Implement and display:


Max & Min (with indices)


Vector length


Sorted version (both row-wise descending and entire matrix descending)


Sum, Product


Median, Mean, Standard Deviation


📌 Hint: Use np.sort() with axis=1 for row-wise sorting. Use .flatten() for entire matrix sorting.


In [3]:
# Creating a 2x3 matrix can have float values
vec = np.array([[1.5, 2, 3.1], [4, 5, 6.5]])

max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 6.5 at index 5
Min value: 1.5 at index 0
Length of vector: 2
Sorted vector: [[1.5 2.  3.1]
 [4.  5.  6.5]]
Sum of elements: 22.1
Product of elements: 1209.0
Median value: 3.55
Mean value: 3.6833333333333336
Standard deviation: 1.717960677340692
